version: '2'

services:
    php-fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        links:
            - db
            - elasticsearch
        ports:
            - 9000:9000
            - 8448:8448
            - 8910:8910
        working_dir: /var/www/html/
        volumes:
            - ./app:/var/www/html
            - /var/www/shared
        volumes_from:
            - data
        tty: true
        command: sh /root/command.sh
        networks:
            mynet:
                ipv4_address: 172.12.1.2

    nginx:
        image: nginx
        links:
            - php-fpm
        ports:
            - 80:80
            - 8081:8081
            - 443:443
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx/conf.d/search_engine.conf:/etc/nginx/conf.d/search_engine.conf
            - ./docker/nginx/certificates:/etc/nginx/certificates
        volumes_from:
            - php-fpm
            - data
        networks:
            mynet:
                ipv4_address: 172.12.1.4

    db:
        image: mariadb:10.1
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
        command: --max_allowed_packet=32505856
        volumes_from:
            - data
        networks:
            mynet:
                ipv4_address: 172.12.1.5

    data:
        image: debian
        working_dir: /
        volumes:
            - /var/lib/mysql
            - /var/log/nginx
            - /data
        tty: true

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        ports:
            - 9200:9200
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
        networks:
            mynet:
                ipv4_address: 172.12.1.8

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8080:80
        networks:
            mynet:
                ipv4_address: 172.12.1.10


networks:
    mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.12.0.0/16
                  gateway: 172.12.5.254                
